# Impression.create!([
  # {impressionable_type: "Topic", impressionable_id: 1, user_id: nil, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "03ebaa4a66b180a0714ebda9e8d8bd313ee3e73be09f80756827a0765a5dc95c", ip_address: "::1", session_hash: "dc3637d318880a1d866e74f3c3942ca3", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 2, user_id: nil, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "c279bdd71e5b568ed02078d98e71445fea2dbe271e26708cf73734448a3b931a", ip_address: "::1", session_hash: "dc3637d318880a1d866e74f3c3942ca3", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 1, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "0fc630668476c57a8a01515b572754bbc775682104447795cc81c4f2716b7c12", ip_address: "::1", session_hash: "f36bdd317a1ef1983749126a3db90396", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 2, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "c949da92ff044eb702da9d5fb2d9023d974ddb831a73d18eec399ce4f8292e0d", ip_address: "::1", session_hash: "f36bdd317a1ef1983749126a3db90396", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 2, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "81617b56ff8fbc2ae2207cd8ac1d09f7cdc23310a5f6a054c979460d8649006e", ip_address: "::1", session_hash: "03ea395cce6224ca43610eacf9a895e6", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 1, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "9847414ae89021f15756c191232f1ebb052d0653d8de66320eee43b87235f5b6", ip_address: "::1", session_hash: "03ea395cce6224ca43610eacf9a895e6", message: nil, referrer: "http://localhost:3000/topics?utf8=%E2%9C%93&q%5Bsorts%5D=title+desc&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Buser_id_eq_any%5D%5B%5D=&q%5Buser_id_eq_any%5D%5B%5D=1&q%5Btitle_cont%5D=&commit=%E3%83%88%E3%83%94%E3%83%83%E3%82%AF%E6%A4%9C%E7%B4%A2", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 4, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "b69ee6026db2e4776a6835bedeeae1ef9d35d4e4c4f0f4a9f00840d2a9c8e586", ip_address: "::1", session_hash: "03ea395cce6224ca43610eacf9a895e6", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 3, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "3ca54db9e2db046014bd105294268a506e5a84c984d560723cb6b4193b302140", ip_address: "::1", session_hash: "03ea395cce6224ca43610eacf9a895e6", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 6, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "54844f481724c4bf0ca1cce486399e3715208b5b18f136040a4b2af86c534786", ip_address: "::1", session_hash: "03ea395cce6224ca43610eacf9a895e6", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 29, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "4dc581d89026ac1715032179591805618cb9f919fbac49696aa25e8e37393172", ip_address: "::1", session_hash: "03ea395cce6224ca43610eacf9a895e6", message: nil, referrer: "http://localhost:3000/?page=2&q%5Bsorts%5D=id+desc", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 28, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "62f827cf3165ebb0f3d3cc42e0815a2dc6a7af6ae1be6f83401e9a7eb4d221a9", ip_address: "::1", session_hash: "03ea395cce6224ca43610eacf9a895e6", message: nil, referrer: "http://localhost:3000/topics?utf8=%E2%9C%93&q%5Bsorts%5D=updated_at+asc&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Buser_id_eq_any%5D%5B%5D=&q%5Btitle_cont%5D=", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 14, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "d9d15cabfac57e7f9a75aeb23fd5573062e04d7d75fd176e8d718022b08bf382", ip_address: "::1", session_hash: "03ea395cce6224ca43610eacf9a895e6", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 3, user_id: nil, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "d6a16d4b7ce0e6415aa3d0680de99756a0a1b13cedd67ded4d1a52b32138bd91", ip_address: "::1", session_hash: "8cf6d2915a780d10c0ed4458d978e23d", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 4, user_id: nil, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "803ede86f3b38a7445226a76738b2be68c1cd601bd22a63637c24fc411f906b6", ip_address: "::1", session_hash: "8cf6d2915a780d10c0ed4458d978e23d", message: nil, referrer: "http://localhost:3000/topics?utf8=%E2%9C%93&q%5Bsorts%5D=updated_at+asc&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Btitle_cont%5D=", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 4, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "11fa4a90c2c06764f6e2a224bf3c324173577bf517537bf028700389086e4b6c", ip_address: "::1", session_hash: "c924c3ae843392113bdb9de51246d3a7", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 48, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "ff98f425fe09c7c0916e70b22c10cf0e00700710f8961c9126771538c37ef95f", ip_address: "::1", session_hash: "c924c3ae843392113bdb9de51246d3a7", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 1, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "abc5bdcdd14c541f18d6ad12231c6ef2bdea260ef858f333bd089ff4eed4674e", ip_address: "::1", session_hash: "c924c3ae843392113bdb9de51246d3a7", message: nil, referrer: "http://localhost:3000/topics?utf8=%E2%9C%93&q%5Bsorts%5D=topic_likes_count+desc&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Buser_id_eq_any%5D%5B%5D=&q%5Btitle_cont%5D=", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 2, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "d20aa6a6cdf0b2d68dc0a10034e74cf1695595c98305e7ab78883f22d5165315", ip_address: "::1", session_hash: "c924c3ae843392113bdb9de51246d3a7", message: nil, referrer: "http://localhost:3000/topics?utf8=%E2%9C%93&q%5Bsorts%5D=topic_likes_count+desc&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Buser_id_eq_any%5D%5B%5D=&q%5Btitle_cont%5D=", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 1, user_id: 2, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "2e9194b719609dcba30f543d93a76148e54f94f85f629dbf318c58d59d9650cc", ip_address: "::1", session_hash: "5fdd6da01d28ac35f87cc83629532f28", message: nil, referrer: "http://localhost:3000/topics?utf8=%E2%9C%93&q%5Bsorts%5D=topic_likes_count+desc&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Buser_id_eq_any%5D%5B%5D=&q%5Btitle_cont%5D=", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 4, user_id: 2, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "5a41f64c0bfbedd86cb88ba13b00fc9c6e717f001a326d0757a524f3f196cd56", ip_address: "::1", session_hash: "5fdd6da01d28ac35f87cc83629532f28", message: nil, referrer: "http://localhost:3000/topics?utf8=%E2%9C%93&q%5Bsorts%5D=topic_likes_count+desc&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Buser_id_eq_any%5D%5B%5D=&q%5Btitle_cont%5D=", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 48, user_id: 2, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "a092380f22d69be192501655a9639ba1b0d038696e966c1d61a4c08da014320b", ip_address: "::1", session_hash: "5fdd6da01d28ac35f87cc83629532f28", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 49, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "a31b539ffb45397685355782a4633bd08183e605d978853792941af2bcb1a1d1", ip_address: "::1", session_hash: "94f979163cee46b19a6db6d6b4d77579", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 48, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "f498c2af9ed90b950d46ee5b4917ab36dc19654414c97a6752ab512cad6c9cc2", ip_address: "::1", session_hash: "94f979163cee46b19a6db6d6b4d77579", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 3, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "4abff5eaf93cbc99931d47d4d7461e1747df4e1d5d0f4be18f50c18358469c4e", ip_address: "::1", session_hash: "94f979163cee46b19a6db6d6b4d77579", message: nil, referrer: "http://localhost:3000/topics?utf8=%E2%9C%93&q%5Bsorts%5D=topic_likes_count+desc&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Buser_id_eq_any%5D%5B%5D=&q%5Btitle_cont%5D=", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 4, user_id: 1, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "8e05d9a4a48ce4d2a76cfcf3612b84d213976ce7b204a9dd61f591af09ddff47", ip_address: "::1", session_hash: "94f979163cee46b19a6db6d6b4d77579", message: nil, referrer: "http://localhost:3000/topics?utf8=%E2%9C%93&q%5Bsorts%5D=topic_likes_count+desc&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Buser_id_eq_any%5D%5B%5D=&q%5Btitle_cont%5D=", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 48, user_id: nil, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "8bb7c73a26c3fec28c5386915cb5271d12ad16f66fc45a16d1cc08417b7538dd", ip_address: "::1", session_hash: "20f0543db723258f760cbd10a02fee8e", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 49, user_id: nil, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "706cd8d701ecc3bd16ad435d3db32b4ad9360b3da94c1704531e5054ad86a059", ip_address: "::1", session_hash: "20f0543db723258f760cbd10a02fee8e", message: nil, referrer: "http://localhost:3000/", params: {}},
  # {impressionable_type: "Topic", impressionable_id: 4, user_id: nil, controller_name: "topics", action_name: "show", view_name: nil, request_hash: "3a2098f6238d0304894a2c054e63a714ddad5c531b199ff85263fb16d5cab38d", ip_address: "::1", session_hash: "20f0543db723258f760cbd10a02fee8e", message: nil, referrer: "http://localhost:3000/topics?utf8=%E2%9C%93&q%5Bsorts%5D=impressions_count+desc&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Bcategory_id_eq_any%5D%5B%5D=&q%5Btitle_cont%5D=", params: {}}
# ])
# User.create!([
  # {name: "dvwevq", image: "download-4.jpg", email: "t@t.com", encrypted_password: "$2a$11$s6LCZR3o8IvV4tbhjhVBQO3w6e9/uh70rB/yE/aR4v5rRdGw8tEn6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil},
  # {name: "dfavefve", image: "download-10.jpg", email: "d@d.com", encrypted_password: "$2a$11$c36qgFxh2EfeqRylA5QwRebXD8ltRU0KCodxMtqPGwWg6KflSu9rq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil},
  # {name: "elm", image: nil, email: "test@t.com", encrypted_password: "$2a$11$sJ8NU4nsxRiezNvMpoYS8.IcGsk7VLN4RGjDXdn.Al6QFoFFIUjJy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil},
  # {name: "aaaaaaaaaaaaaaaa", image: nil, email: "a@a.com", encrypted_password: "$2a$11$B7zpXEI3m79acGqnPnUAse2nBI8dtaCMXG5MBSx/NT.gdxoFon7x2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil}
# ])

Topic.create!([
  {title: "wdvewvwvwv", content: "evwfveaveavfe", image: nil, category_id: 2, user_id: 1, impressions_count: 5},
  {title: "aefvaevae", content: "eavfeafvaeea", image: nil, category_id: 2, user_id: 1, impressions_count: 4},
  {title: "aefvaevaev", content: "aefvaeeeeeve", image: nil, category_id: 2, user_id: 1, impressions_count: 3},
  {title: "eavfeafv", content: "eafveavaeeefv", image: nil, category_id: 4, user_id: 1, impressions_count: 6},
  {title: "んjblほjk", content: "svさfdっゔぁっっv", image: nil, category_id: 4, user_id: 1, impressions_count: 0},
  {title: "asvewvwev", content: "aefvaevevvvv", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "sadvasvs", content: "asvasvsfvscv v", image: nil, category_id: 4, user_id: 2, impressions_count: 0},
  {title: "aefvaevaev", content: "aefvaeeeeeve", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "eavfeafv", content: "eafveavaeeefv", image: nil, category_id: 4, user_id: 1, impressions_count: 1},
  {title: "んjblほjk", content: "svさfdっゔぁっっv", image: nil, category_id: 4, user_id: 1, impressions_count: 0},
  {title: "asvewvwev", content: "aefvaevevvvv", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "sadvasvs", content: "asvasvsfvscv v", image: nil, category_id: 4, user_id: 2, impressions_count: 0},
  {title: "aefvaevaev", content: "aefvaeeeeeve", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "eavfeafv", content: "eafveavaeeefv", image: nil, category_id: 4, user_id: 1, impressions_count: 1},
  {title: "んjblほjk", content: "svさfdっゔぁっっv", image: nil, category_id: 4, user_id: 1, impressions_count: 0},
  {title: "asvewvwev", content: "aefvaevevvvv", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "sadvasvs", content: "asvasvsfvscv v", image: nil, category_id: 4, user_id: 2, impressions_count: 0},
  {title: "aefvaevaev", content: "aefvaeeeeeve", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "eavfeafv", content: "eafveavaeeefv", image: nil, category_id: 4, user_id: 1, impressions_count: 1},
  {title: "んjblほjk", content: "svさfdっゔぁっっv", image: nil, category_id: 4, user_id: 1, impressions_count: 0},
  {title: "asvewvwev", content: "aefvaevevvvv", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "sadvasvs", content: "asvasvsfvscv v", image: nil, category_id: 4, user_id: 2, impressions_count: 0},
  {title: "aefvaevaev", content: "aefvaeeeeeve", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "eavfeafv", content: "eafveavaeeefv", image: nil, category_id: 4, user_id: 1, impressions_count: 1},
  {title: "んjblほjk", content: "svさfdっゔぁっっv", image: nil, category_id: 4, user_id: 1, impressions_count: 0},
  {title: "asvewvwev", content: "aefvaevevvvv", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "sadvasvs", content: "asvasvsfvscv v", image: nil, category_id: 4, user_id: 2, impressions_count: 0},
  {title: "aefvaevaev", content: "aefvaeeeeeve", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "eavfeafv", content: "eafveavaeeefv", image: nil, category_id: 4, user_id: 1, impressions_count: 1},
  {title: "んjblほjk", content: "svさfdっゔぁっっv", image: nil, category_id: 4, user_id: 1, impressions_count: 0},
  {title: "asvewvwev", content: "aefvaevevvvv", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "sadvasvs", content: "asvasvsfvscv v", image: nil, category_id: 4, user_id: 2, impressions_count: 0},
  {title: "aefvaevaev", content: "aefvaeeeeeve", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "eavfeafv", content: "eafveavaeeefv", image: nil, category_id: 4, user_id: 1, impressions_count: 1},
  {title: "んjblほjk", content: "svさfdっゔぁっっv", image: nil, category_id: 4, user_id: 1, impressions_count: 0},
  {title: "asvewvwev", content: "aefvaevevvvv", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "sadvasvs", content: "asvasvsfvscv v", image: nil, category_id: 4, user_id: 2, impressions_count: 0},
  {title: "aefvaevaev", content: "aefvaeeeeeve", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "eavfeafv", content: "eafveavaeeefv", image: nil, category_id: 4, user_id: 1, impressions_count: 1},
  {title: "んjblほjk", content: "svさfdっゔぁっっv", image: nil, category_id: 4, user_id: 1, impressions_count: 0},
  {title: "asvewvwev", content: "aefvaevevvvv", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "sadvasvs", content: "asvasvsfvscv v", image: nil, category_id: 4, user_id: 2, impressions_count: 0},
  {title: "aefvaevaev", content: "aefvaeeeeeve", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "eavfeafv", content: "eafveavaeeefv", image: nil, category_id: 4, user_id: 1, impressions_count: 1},
  {title: "んjblほjk", content: "svさfdっゔぁっっv", image: nil, category_id: 4, user_id: 1, impressions_count: 0},
  {title: "asvewvwev", content: "aefvaevevvvv", image: nil, category_id: 2, user_id: 1, impressions_count: 1},
  {title: "sadvasvs", content: "asvasvsfvscv v", image: nil, category_id: 4, user_id: 2, impressions_count: 0},
  {title: "aefvaevaev", content: "aefvaeeeeeve", image: nil, category_id: 2, user_id: 1, impressions_count: 4},
  {title: "eavfeafv", content: "eafveavaeeefv", image: nil, category_id: 4, user_id: 1, impressions_count: 2}
])
Comment.create!([
  {content: "eafveavaevea", image: nil, topic_id: 2, user_id: 1},
  {content: "esfvasvaefvaeve", image: nil, topic_id: 2, user_id: 1},
  {content: "eavavaevevfeaevre", image: nil, topic_id: 2, user_id: 1},
  {content: "erfwvwv", image: nil, topic_id: 1, user_id: 1},
  {content: "asfdsvwavwvwfa", image: nil, topic_id: 1, user_id: 1},
  {content: "erabagrrreaavggg", image: nil, topic_id: 1, user_id: 1},
  {content: "dafvaevaeveeeeeeerrrr", image: nil, topic_id: 1, user_id: 1},
  {content: "dafvadvaevvvvvv", image: nil, topic_id: 1, user_id: 1},
  {content: "efvaevewvrwavww", image: nil, topic_id: 4, user_id: 1},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "grwwwwwwbt", image: "download-8.jpg", topic_id: 2, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "grwwwwwwbt", image: "download-8.jpg", topic_id: 2, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "grwwwwwwbt", image: "download-8.jpg", topic_id: 2, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "grwwwwwwbt", image: "download-8.jpg", topic_id: 2, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "grwwwwwwbt", image: "download-8.jpg", topic_id: 2, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "asvfawvwvvvwf", image: nil, topic_id: 3, user_id: 2},
  {content: "sfavaesvaevfaasfv", image: nil, topic_id: 4, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "svwweafvev", image: nil, topic_id: 3, user_id: 2},
  {content: "grwwwwwwbt", image: "download-8.jpg", topic_id: 2, user_id: 1},
  {content: "sadvwvawvvearverg", image: nil, topic_id: 4, user_id: 1},
  {content: "sadfvaesveasvawv", image: nil, topic_id: 3, user_id: 2},
  {content: "eeee", image: "download-4.jpg", topic_id: 4, user_id: 1},
  {content: "eeee", image: nil, topic_id: 4, user_id: 1},
  {content: "eeee", image: nil, topic_id: 4, user_id: 1},
  {content: "eeee", image: nil, topic_id: 4, user_id: 1}
])
CommentLike.create!([
  {comment_id: 2, user_id: 1},
  {comment_id: 1, user_id: 1},
  {comment_id: 6, user_id: 1},
  {comment_id: 9, user_id: 1},
  {comment_id: 12, user_id: 2},
  {comment_id: 14, user_id: 2},
  {comment_id: 10, user_id: 2},
  {comment_id: 9, user_id: 2},
  {comment_id: 2, user_id: 2},
  {comment_id: 3, user_id: 2},
  {comment_id: 5, user_id: 2},
  {comment_id: 6, user_id: 2},
  {comment_id: 4, user_id: 2},
  {comment_id: 4, user_id: 1},
  {comment_id: 7, user_id: 1},
  {comment_id: 65, user_id: 1},
  {comment_id: 61, user_id: 1},
  {comment_id: 46, user_id: 1},
  {comment_id: 41, user_id: 1},
  {comment_id: 23, user_id: 1},
  {comment_id: 14, user_id: 1},
  {comment_id: 19, user_id: 1},
  {comment_id: 44, user_id: 1},
  {comment_id: 8, user_id: 2},
  {comment_id: 7, user_id: 2},
  {comment_id: 61, user_id: 2}
])
Enquete.create!([
  {content: "feavaeveav", topic_id: 1},
  {content: "feaveeavfa", topic_id: 1},
  {content: "aefvaevev", topic_id: 2},
  {content: "fevvavf", topic_id: 3},
  {content: "eafvevfvev", topic_id: 3},
  {content: "aeffvae", topic_id: 4},
  {content: "feveve", topic_id: 4},
  {content: "aevaev", topic_id: 6},
  {content: "fdvvvvvvvvvvvvvvvvvvvvv", topic_id: 6},
  {content: "scvsdvsv", topic_id: 7},
  {content: "fsadvaevfewvwveevve", topic_id: 7}
])
TopicLike.create!([
  {topic_id: 1, user_id: 1},
  {topic_id: 2, user_id: 1},
  {topic_id: 4, user_id: 1},
  {topic_id: 4, user_id: 2},
  {topic_id: 48, user_id: 2}
])
Vote.create!([
  {enquete_id: 1, user_id: 1},
  {enquete_id: 3, user_id: 1}
])
